### ISSUE TITLE
指标计算代码

### ISSUE THREAD

**Issue by HJHGJGHHG** [tanshuai0219/EDTalk#10]
优秀的开源工作！请问能发布计算指标的代码吗？infer的结果在我们的指标评估代码上表现不好，希望用你们的代码试试

**Comment by tanshuai0219** [comment]
你好，指标计算我们更多的是参考
https://github.com/yuangan/evaluation_eat
这个project

**Comment by junleen** [comment]
请问一下测试wav2lip的时候，是只用一张图片吗？合成若干帧后跟groundtruth做PSNR/SSIM loss？

**Comment by tanshuai0219** [comment]
> 请问一下测试wav2lip的时候，是只用一张图片吗？合成若干帧后跟groundtruth做PSNR/SSIM loss？

为了保证输入的一致性，是这样做的

**Comment by dttttttyfyfyf** [comment]
> 优秀的开源工作！请问能发布计算指标的代码吗？infer的结果在我们的指标评估代码上表现不好，希望用你们的代码试试

你好，请问你写出来了嘛，可以分享一下嘛
