### ISSUE TITLE
trainning code realse plan

### ISSUE THREAD

**Issue by jennysunny** [tanshuai0219/EDTalk#11]
Nice job. Will have any plan release  train code?

**Comment by tanshuai0219** [comment]
Yes, we will release the training codes. Please leave a star and stay tuned, Thanks.

**Comment by jennysunny** [comment]
sure，Looking forward to it

**Comment by tanshuai0219** [comment]
> sure，Looking forward to it

Hi, I release part of the training codes. However, due to the limited time available, the code hasn't been completely cleaned. Considering this is still a good reference, I'm still releasing the code. If you run into any problems, please feel free to leave an issue. I'll try to take the time to improve the code as much as possible.

**Comment by jennysunny** [comment]
Great. In addition, expressions are the module I care about most. I will reproduce them based on the train code you have released. hope you can add this content if you have time, thank you so much

**Comment by tanshuai0219** [comment]
> Great. In addition, expressions are the module I care about most. I will reproduce them based on the train code you have released. hope you can add this content if you have time, thank you so much

Thanks for your patience～ I will release the corresponding codes as soon as possible.

**Comment by jennysunny** [comment]
您好，我正在尝试浮现EDtalk表情部分的实验，目前已经将ELN和EEM模块添加到自己的LIA模型中，并通过多情感数据集进行fine-tune(添加FRNet和deca encoder中的loss)，但在实际测试中发现指定不同表情的图像对生成结果基本没影响，请问我在具体实验中有什么遗漏的地方吗？
by the way，在论文ablation中w/o Bank是影响效果的一个很重要的点，请问这个bank具体指什么。期待您的回复

**Comment by tanshuai0219** [comment]
> 您好，我正在尝试浮现EDtalk表情部分的实验，目前已经将ELN和EEM模块添加到自己的LIA模型中，并通过多情感数据集进行fine-tune(添加FRNet和deca encoder中的loss)，但在实际测试中发现指定不同表情的图像对生成结果基本没影响，请问我在具体实验中有什么遗漏的地方吗？

可以先去掉FRNet和deca encoder loss，先只更新ELN和EEM的参数，比较收敛之后，可以尝试下把dec也进行微调

**Comment by jennysunny** [comment]
> > 您好，我正在尝试浮现EDtalk表情部分的实验，目前已经将ELN和EEM模块添加到自己的LIA模型中，并通过多情感数据集进行fine-tune(添加FRNet和deca encoder中的loss)，但在实际测试中发现指定不同表情的图像对生成结果基本没影响，请问我在具体实验中有什么遗漏的地方吗？
> 
> 可以先去掉FRNet和deca encoder loss，先只更新ELN和EEM的参数，比较收敛之后，可以尝试下把dec也进行微调

好的，我来尝试下，多谢
