### ISSUE TITLE
Question about requirements

### ISSUE THREAD

**Issue by arpita2512** [tanshuai0219/EDTalk#12]
Hi, thank you for open-sourcing your work.
I tried running the inference code and it seems that your requirement file is missing tqdm and librosa.
Also, please could you let me know what version of ffmpeg you used?

**Comment by tanshuai0219** [comment]
> Hi, thank you for open-sourcing your work. I tried running the inference code and it seems that your requirement file is missing tqdm and librosa. Also, please could you let me know what version of ffmpeg you used?

 Hi, sorry for the delayed response. The requirement.txt has been updated, and we use ffmpeg version 5.0.1. 

Thanks for your interest and attention.

**Comment by tanshuai0219** [comment]
> Hi, thank you for open-sourcing your work. I tried running the inference code and it seems that your requirement file is missing tqdm and librosa. Also, please could you let me know what version of ffmpeg you used?

We added a face super-resolution module which upscale the resolution from 256 to 512 and address the issue of blurry rendering. Welcome to try.
