### ISSUE TITLE
Am I allowed to use some code from this project

### ISSUE THREAD

**Issue by nitinmukesh** [tanshuai0219/EDTalk#14]
Hello,

I do not see any LICENSE information.

I want to use the following code as a standalone tool for different project (AniTalker). I am not associated with that project

https://raw.githubusercontent.com/tanshuai0219/EDTalk/main/data_preprocess/crop_image2.py

Is it fine to create a new git repo using the above code with Gradio interface? Due credit to EDTalk will be given

No financial gain just free tool for users

**Comment by tanshuai0219** [comment]
It is ok~ You are welcome!

**Comment by nitinmukesh** [comment]
Thank you
