### ISSUE TITLE
EDTalk交流群，欢迎交流~

### ISSUE THREAD

**Issue by tanshuai0219** [tanshuai0219/EDTalk#22]
![EDTalk_wechat](https://github.com/user-attachments/assets/165fa3d5-bf63-4a70-adb7-86cf7c2dcc46)

**Comment by mhsin321** [comment]
why not HF demo online hmm

**Comment by tanshuai0219** [comment]
> why not HF demo online hmm

I'll try it later~

**Comment by duyuankai1992** [comment]
EDTalk交流群的群照片能更新一下嘛，到期啦

**Comment by tanshuai0219** [comment]
> EDTalk交流群的群照片能更新一下嘛，到期啦

加我微信吧 我拉你进群 tanshuai20010219

**Comment by dttttttyfyfyf** [comment]
> > EDTalk交流群的群照片能更新一下嘛，到期啦
> 
> 加我微信吧 我拉你进群 tanshuai20010219



> > EDTalk交流群的群照片能更新一下嘛，到期啦
> 
> 加我微信吧 我拉你进群 tanshuai20010219

可以拉我嘛dtt213202，我加您发现没办法搜索到
