### ISSUE TITLE
Confusion regarding training process

### ISSUE THREAD

**Issue by avgAnimeOtaku** [tanshuai0219/EDTalk#27]
If I am using only demo_lip_pose_V.py and I want to train this model with my own data, then do I need to run train/train_E_G.py, train/train_Mouth_Pose_decouple.py and train/train_audio2mouth.py or do I only need to run train/train_Mouth_Pose_decouple.py

**Comment by tanshuai0219** [comment]
Hi, you need to run train/train_E_G.py and train/train_Mouth_Pose_decouple.py. But the current codes are not cleaned, so you need to clean the code by yourself.

**Comment by avgAnimeOtaku** [comment]
Thank you for your help!
