### ISSUE TITLE
网络的输出分辨率是多少，演示视频的牙齿好像很模糊

### ISSUE THREAD

**Issue by kike-0304** [tanshuai0219/EDTalk#3]

**Comment by tanshuai0219** [comment]
分辨率是256*256的，有些case确实会存在牙齿模糊，这也是当前较低分辨率 generator的通病，如fomm， pirender等。当前开源的用diffusion model ，如[AniPortrait](https://github.com/Zejun-Yang/AniPortrait)生成的分辨率会更高一矮，但牙齿部分的建模仍然比较奇怪，另外，这样的模型推理比较慢，且需要较大的计算资源，我目前还没有能力支付这样的算力进行训练。

可以参考sadtalker的后处理方式，用[codeformer](https://github.com/sczhou/CodeFormer)或者[MetaPortrait](https://github.com/Meta-Portrait/MetaPortrait)来对生成的视频进行高分辨率视频的生成。

**Comment by xiao-keeplearning** [comment]
你好，问下你有研究过微软的vasa-1么，那个看demo效果挺好而且速度快

**Comment by tanshuai0219** [comment]
> 你好，问下你有研究过微软的vasa-1么，那个看demo效果挺好而且速度快

我对vasa-1还是挺感兴趣的，无奈不开源，只能望洋兴叹了

**Comment by HJHGJGHHG** [comment]
> 你好，问下你有研究过微软的vasa-1么，那个看demo效果挺好而且速度快

VASA的render用的是[MegaPortraits (Drobyshev et al., @ MM 22)](https://arxiv.org/pdf/2207.07621)，一作最新的工作[EMOPortraits (@ CVPR 24)](https://neeek2303.github.io/EMOPortraits/)计划这两个月开源，与MegaPortraits方法接近，可以关注一下

**Comment by tanshuai0219** [comment]
> > 你好，问下你有研究过微软的vasa-1么，那个看demo效果挺好而且速度快
> 
> VASA的render用的是[MegaPortraits (Drobyshev et al., @ MM 22)](https://arxiv.org/pdf/2207.07621)，一作最新的工作[EMOPortraits (@ CVPR 24)](https://neeek2303.github.io/EMOPortraits/)计划这两个月开源，与MegaPortraits方法接近，可以关注一下

嗯嗯 我知道的 也一直在关注

**Comment by piwawa** [comment]
> > 你好，问下你有研究过微软的vasa-1么，那个看demo效果挺好而且速度快
> 
> VASA的render用的是[MegaPortraits (Drobyshev et al., @ MM 22)](https://arxiv.org/pdf/2207.07621)，一作最新的工作[EMOPortraits (@ CVPR 24)](https://neeek2303.github.io/EMOPortraits/)计划这两个月开源，与MegaPortraits方法接近，可以关注一下

EMOPortraits 这个项目开源了，不知道咋用啊？能用来替换什么组件吗？
