### ISSUE TITLE
How to get pose_feature, lip_feature in dataset_audio2lip.py?

### ISSUE THREAD

**Issue by Zeyu-Zhu** [tanshuai0219/EDTalk#30]
Thanks for the great work!

I'm going to train audio2mounth model on my own datasets, and I'm wondering how to generate pose_feature, lip_feature for each sample. Btw I already got mel, bbox and lmdb generated.

**Comment by tanshuai0219** [comment]
> Thanks for the great work!
> 
> I'm going to train audio2mounth model on my own datasets, and I'm wondering how to generate pose_feature, lip_feature for each sample. Btw I already got mel, bbox and lmdb generated.

Thanks for your interest!
You can refer to the below codes:
https://github.com/tanshuai0219/EDTalk/blob/5757ca9891d4fb2d05d96d93c0ac67a4256a1331/networks/generator_lip_pose.py#L207

and see how alpha_D_lip and alpha_D_pose are obtained, which are  pose_feature, lip_feature in dataset_audio2lip.py.

**Comment by Zeyu-Zhu** [comment]
Thank you for your quick reply! I generated the feature now. 

But when I'm running 'train_audio2mounth.py', an error occurred:
FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/checkpoint.pth' in  'trainer_audio2mounth.py' line 107. 

Could you inform me where I can get this checkpoint?

**Comment by tanshuai0219** [comment]
> Thank you for your quick reply! I generated the feature now.
> 
> But when I'm running 'train_audio2mounth.py', an error occurred: FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/checkpoint.pth' in 'trainer_audio2mounth.py' line 107.
> 
> Could you inform me where I can get this checkpoint?

The checkpoint should be obtained after run train_E_G.py, which aims to pretrain a encoder and generator.
But the trained checkpoint has some parameters different from the structure of generator in trainer_audio2mounth.py. So when you load checkpoint, you should pay attention to it and load the parameter originally existed in  generator in trainer_audio2mounth.py
