### ISSUE TITLE
The pretrained resume_ckpt in train_audio2mounth.py

### ISSUE THREAD

**Issue by Zeyu-Zhu** [tanshuai0219/EDTalk#32]
Thanks!

Can I kindly ask for this pre-trained model? Or where can I find it?

**Comment by tanshuai0219** [comment]
> Thanks!
> 
> Can I kindly ask for this pre-trained model? Or where can I find it?

It's actually the model which you get feature in https://github.com/tanshuai0219/EDTalk/issues/30#issuecomment-2342853054

I recommend you reading paper again and work out the multistage training strategy~

**Comment by Zeyu-Zhu** [comment]
Thanks for the help. I will try to figure it out.
