### ISSUE TITLE
请问能只生成带情感的，头部姿态不动吗？

### ISSUE THREAD

**Issue by sunnymoon155** [tanshuai0219/EDTalk#36]
感谢回答，如果可以的话用哪个代码呢？

**Comment by tanshuai0219** [comment]
可以修改下
`
python demo_EDTalk_A_using_predefined_exp_weights.py --source_path res/results_by_facesr/demo_EDTalk_A.png --audio_driving_path test_data/mouth_source.wav --pose_driving_path test_data/pose_source1.mp4 --exp_type angry --save_path res/demo_EDTalk_A_using_weights.mp4
`
这个代码，把pose_driving_path 给一个固定的pose

**Comment by sunnymoon155** [comment]
> 可以修改下 `python demo_EDTalk_A_using_predefined_exp_weights.py --source_path res/results_by_facesr/demo_EDTalk_A.png --audio_driving_path test_data/mouth_source.wav --pose_driving_path test_data/pose_source1.mp4 --exp_type angry --save_path res/demo_EDTalk_A_using_weights.mp4` 这个代码，把pose_driving_path 给一个固定的pose

感谢大佬回复，我试用了一下发现lip_video+lip_audio的驱动方式要比纯audio驱动的效果好很多，这个是正常的结果吗？如果单纯用audio驱动的话还有优化空间吗？
