### ISSUE TITLE
开源训练代码

### ISSUE THREAD

**Issue by HuaizeLiu** [tanshuai0219/EDTalk#6]
请问论文接受后，会放出训练代码吗？

**Comment by tanshuai0219** [comment]
会的，我会抽时间整理，复现代码，计划一步一步放出训练代码，比如 1.开源训练原始encoder-decoder的代码 （类似于face reenactment）2. lip-nonlip disentanglement code 3. audio2lip code 4.......

**Comment by junleen** [comment]
请问一下测试wav2lip的时候，是只用一张图片吗？合成若干帧后跟groundtruth做PSNR/SSIM loss？

**Comment by tanshuai0219** [comment]
> 请问一下测试wav2lip的时候，是只用一张图片吗？合成若干帧后跟groundtruth做PSNR/SSIM loss？

对的
