### ISSUE TITLE
Missing 'wav2lip.pth'

### ISSUE THREAD

**Issue by QUTGXX** [tanshuai0219/EDTalk#7]
Thank you for sharing this great work and making it open source. However, when I run it, I encounter a missing file issue: 'No such file or directory: '/data/ts/code/comparison/Wav2Lip/checkpoints/wav2lip.pth'. Could you please help with this?

**Comment by tanshuai0219** [comment]
Thanks for pointing out the problem, we've fixed it, please pull the latest code!

**Comment by QUTGXX** [comment]
> Thanks for pointing out the problem, we've fixed it, please pull the latest code!
I am also missing the files 'crop_img.py' and 'crop_video.py'. Could you please provide these files or let me know where to find them? Thank you!

**Comment by tanshuai0219** [comment]
> > Thanks for pointing out the problem, we've fixed it, please pull the latest code!
> 
> I am also missing the files 'crop_img.py' and 'crop_video.py'. Could you please provide these files or let me know where to find them? Thank you!

sorry for the missing files... We've added them. If you meet any other questions, please feel free to leave a message~

**Comment by tanshuai0219** [comment]
> > Thanks for pointing out the problem, we've fixed it, please pull the latest code!
> 
> I am also missing the files 'crop_img.py' and 'crop_video.py'. Could you please provide these files or let me know where to find them? Thank you!

You can also have my WeChat: tanshuai20010219 for more efficient communication.
