### ISSUE TITLE
可以像wav2lip一样只推理嘴吗?

### ISSUE THREAD

**Issue by laishujie** [tanshuai0219/EDTalk#9]

**Comment by tanshuai0219** [comment]
可以的，有空我会提交一版相关的代码

**Comment by tanshuai0219** [comment]
相关代码已经更新，欢迎使用~

**Comment by laishujie** [comment]
> 相关代码已经更新，欢迎使用~

感谢，发现几个问题
1. python demo_lip_pose.py  --fix_pose False ，打印的fix_post参数值还是True，可能要改为action="store_true"的方式
2. source_path能接受视频吗？不然我指定pose_driving_path的时候，我的眨眼效果没了。

**Comment by tanshuai0219** [comment]
> > 相关代码已经更新，欢迎使用~
> 
> 感谢，发现几个问题
> 
> 1. python demo_lip_pose.py  --fix_pose False ，打印的fix_post参数值还是True，可能要改为action="store_true"的方式
> 2. source_path能接受视频吗？不然我指定pose_driving_path的时候，我的眨眼效果没了。

第一个 好的，我试下~
第二个，这个我还真没试过，不过我感觉是可以的，如果你方便的话 你可以写下相关的代码 很容易哒~

**Comment by laishujie** [comment]
没问题，我自己写好了，毕竟是我的个人需求。谢了
